import Foundation

// ---- Leccion 7: 51 La proramación Orientasda a Objetos ----


// ¿Qué es la Programación Orientada a Objetos?

// La Programación Orientada a Objetos (POO)...
// es un paradigma de programación, es decir,...
// un modelo o un estilo de programación que ...
// nos da unas guías sobre cómo trabajar con él.
// Se basa en el concepto de clases y objetos.
// Este tipo de programación se utiliza para...
// estructurar un programa de software en piezas...
// simples y reutilizables de planos de código...
// (clases) para crear instancias individuales de objetos.

