import Foundation


// ----- Tuplas (Tuples): -----


// Una tupla es una estructura de datos que permite...
// agrupar múltiples valores en un solo valor compuesto.
// A diferencia de otros tipos de datos como arrays...
// o sets, las tuplas pueden contener...
// elementos de diferentes tipos.
// Las tuplas son especialmente útiles cuando se quiere...
// combinar varios valores de manera temporal...
// y no se desea crear una estructura más...
// compleja para representarlos.

// La sintaxis básica de una tupla en Swift es la siguiente:

let miTupla = (valor1, valor2, valor3)

// Aquí, miTupla es una tupla que contiene tres elementos.
// Puedes acceder a cada elemento utilizando la notación...
// de punto seguida por el índice del elemento:

let primerValor = miTupla.0
let segundoValor = miTupla.1
let tercerValor = miTupla.2

// Además, Swift permite etiquetar los elementos...
// de una tupla, lo que hace que sea más claro...
// y legible acceder a los valores mediante un nombre:

let miTuplaConEtiquetas = (nombre: "Juan", edad: 25, ciudad: "Barcelona")
let nombre = miTuplaConEtiquetas.nombre
let edad = miTuplaConEtiquetas.edad
let ciudad = miTuplaConEtiquetas.ciudad

// En este ejemplo, la tupla tiene etiquetas...
// (nombre, edad, ciudad), lo que facilita la...
// referencia a los elementos de la tupla.

// Además, es posible crear tuplas...
// con valores de diferentes tipos:

let tuplaMixta = ("Texto", 42, 3.14)

// Las tuplas son inmutables por defecto,...
// lo que significa que una vez que se crean,...
// no se pueden modificar. Sin embargo,...
// puedes asignar nuevos valores a las...
// variables que contienen tuplas para...
// cambiar su contenido.

// Las tuplas son utilizadas comúnmente...
// para devolver múltiples valores desde...
// una función sin necesidad de definir...
// una estructura de datos adicional.
// Por ejemplo:

func obtenerCoordenadas() -> (Double, Double) {
    // Cálculos para obtener coordenadas
    let latitud = 40.7128
    let longitud = -74.0060
    return (latitud, longitud)
}

let coordenadas = obtenerCoordenadas()
print("Latitud: \(coordenadas.0), Longitud: \(coordenadas.1)")

// En resumen, las tuplas en Swift proporcionan...
// una manera conveniente de agrupar y manipular...
// un conjunto de valores relacionados,...
// ya sea temporalmente en una función...
// o de manera más general en el código.
//
